[info]
game-name = "tpgz"
full-game-name = "Twilight Princess Practice Rom"
developer-name = "Twilight Princess Community"
full-developer-name = "Speedrun Community"

[src]
iso = "@srcIso"
patch = "regional-patch.asm"
map = "@srcMap"

[build]
map = "@bldMap"
iso = "@bldIso"

[link]
entries = ["apply_lib_hooks"]
base = "@linkBase"
libs = ["tpgz.a", "external/libtp_c/libtp_c.a", "external/gcn_c/gcn_c.a"]

[files]
# textures
"tpgz/tex/file.tex" = "res/tex/file.tex"
"tpgz/tex/folder_empty.tex" = "res/tex/folder_empty.tex"
"tpgz/tex/folder_full.tex" = "res/tex/folder_full.tex"
"tpgz/tex/blank.tex" = "res/tex/blank.tex"
"tpgz/tex/tpgz.tex" = "res/tex/tpgz.tex"
"tpgz/tex/flagOn.tex" = "res/tex/flagOn.tex"
"tpgz/tex/flagOff.tex" = "res/tex/flagOff.tex"
"tpgz/tex/framePlay.tex" = "res/tex/framePlay.tex"
"tpgz/tex/framePause.tex" = "res/tex/framePause.tex"

# fonts
"tpgz/fonts" = "res/fonts"

# any% saves
"tpgz/save_files/any.bin" = "@savesPath/any.bin"
"tpgz/save_files/any" = "@savesPath/any"

# 100% saves
"tpgz/save_files/hundo.bin" = "res/save_files/hundo.bin"
"tpgz/save_files/hundo" = "res/save_files/hundo"

# All Dungeons saves
"tpgz/save_files/ad.bin" = "res/save_files/ad.bin"
"tpgz/save_files/ad" = "res/save_files/ad"

# warp info
"tpgz/stage_info" = "res/stage_info"